sonata_admin:
    title: 'Hirschmann – LPA'
    title_logo: HCC_logo.jpg
    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    assets:
        extra_javascripts:
#            - bundles/sonatapage/app.js
        extra_stylesheets:
            - admin/admin_extra.css
    dashboard:
        blocks:
            - { class: col, position: top, type: admin.question_answer_statistics, settings: { code: admin.answer_summary, text: itt, color: bg-light-grey } }
            - { type: sonata.admin.block.admin_list, position: left, settings: { groups: [LPA, System]} }
            - { type: sonata.admin.block.admin_list, position: right, settings: { groups: [sonata_user, sonata_media, sonata_classification]} }
            

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
