sonata_admin:
    title: 'Hirschmann – LPA'
    title_logo: HCC_logo.jpg
    assets:
        extra_javascripts:
            - bundles/sonatapage/app.js
        extra_stylesheets:
            - bundles/sonatapage/app.css
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            - { class: col-lg-3 col-xs-6, position: right, type: admin.question_answer_statistics, settings: { code: admin.question_answer, icon: fas fa-magic, text: itt, color: bg-light-grey } }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
