sonata_admin:
    title: 'Hirschmann – LPA'
    title_logo: HCC_logo.jpg
    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    assets:
        # all `stylesheets`, `extra_stylesheets`, `remove_stylesheets`,
        # `javascripts`, `extra_javascripts` and `remove_javascripts`
        # can be simple strings or {path, package_name} pairs in case you have to set specific package name for the asset
        stylesheets:

            # The default stylesheet list:
            - bundles/sonataadmin/app.css
            - bundles/sonataform/app.css

        # stylesheets to add to the page in addition to the list above
        extra_stylesheets: [admin/admin_extra.css]

        # stylesheet paths to remove from the page
        remove_stylesheets: []

        javascripts:

            # The default javascript list:
            - bundles/sonataadmin/app.js
            - bundles/sonataform/app.js

        # javascripts to add to the page in addition to the list above
        extra_javascripts: []

        # javascript paths to remove from the page
        remove_javascripts: []
    dashboard:
        blocks:
            - { class: col, position: top, type: admin.question_answer_statistics, settings: { code: admin.answer_summary, text: itt, color: bg-light-grey } }
            - { type: sonata.admin.block.admin_list, position: left, settings: { groups: [LPA, System]} }
            - { type: sonata.admin.block.admin_list, position: right, settings: { groups: [sonata_user, sonata_media, sonata_classification]} }
            

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
