# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.product:
        class: App\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Product, manager_type: orm, label: Product, group: System, icon: '<i class="fa fa-gears"></i>' }
            
    admin.table_group:
        class: App\Admin\TableGroupAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\TableGroup, manager_type: orm, label: Table Group, group: System, icon: '<i class="fa fa-gears"></i>' }
            
    admin.question:
        class: App\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Question, manager_type: orm, label: Question, group: LPA, icon: '<i class="fa fa-bar-chart"></i>' }

    admin.question_answer:
        class: App\Admin\QuestionAnswerAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\QuestionAnswer, manager_type: orm, label: Question Answer, group: LPA, icon: '<i class="fa fa-bar-chart"></i>' }